config/routes.rb
Oratest::Application.routes.draw do
  resources :reservations

  resources :users

  resources :beam_targets
  root:to => 'beam_targets#index'

end

app/models/beam_target.rb
class BeamTarget < ActiveRecord::Base
  attr_accessible :density, :volume
  validates_presence_of :density 
  scope:small, where("volume < 20")
  scope:light, where("density < 2")
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :date, :user_id, :beam_target_id
  belongs_to :user
  belongs_to :beam_target

  validates_presence_of :user,
    message: 'Benutzer ist nicht vorhanden'			
  validates_presence_of :beam_target, 
    message: 'BeamTarget ist nicht vorhanden'  
  validates_presence_of :date
  validates_uniqueness_of :date,
    scope: :beam_target_id,
    message: 'Ist bereits gebucht'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname
  validates_presence_of :lastname, :firstname, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beam_targets_controller.rb
class BeamTargetsController < ApplicationController
  # GET /beam_targets
  # GET /beam_targets.json
  def index
    @beam_targets = BeamTarget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beam_targets }
    end
  end

  # GET /beam_targets/1
  # GET /beam_targets/1.json
  def show
    @beam_target = BeamTarget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beam_target }
    end
  end

  # GET /beam_targets/new
  # GET /beam_targets/new.json
  def new
    @beam_target = BeamTarget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beam_target }
    end
  end

  # GET /beam_targets/1/edit
  def edit
    @beam_target = BeamTarget.find(params[:id])
  end

  # POST /beam_targets
  # POST /beam_targets.json
  def create
    @beam_target = BeamTarget.new(params[:beam_target])

    respond_to do |format|
      if @beam_target.save
        format.html { redirect_to @beam_target, notice: 'Beam target was successfully created.' }
        format.json { render json: @beam_target, status: :created, location: @beam_target }
      else
        format.html { render action: "new" }
        format.json { render json: @beam_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beam_targets/1
  # PUT /beam_targets/1.json
  def update
    @beam_target = BeamTarget.find(params[:id])

    respond_to do |format|
      if @beam_target.update_attributes(params[:beam_target])
        format.html { redirect_to @beam_target, notice: 'Beam target was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beam_target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beam_targets/1
  # DELETE /beam_targets/1.json
  def destroy
    @beam_target = BeamTarget.find(params[:id])
    @beam_target.destroy

    respond_to do |format|
      format.html { redirect_to beam_targets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beam_targets_helper.rb
module BeamTargetsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beam_targets/_form.html.erb
<%= form_for(@beam_target) do |f| %>
  <% if @beam_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beam_target.errors.count, "error") %> prohibited this beam_target from being saved:</h2>

      <ul>
      <% @beam_target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :density %><br />
    <%= f.number_field :density %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.number_field :volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beam_targets/edit.html.erb
<h1>Editing beam_target</h1>

<%= render 'form' %>

<%= link_to 'Show', @beam_target %> |
<%= link_to 'Back', beam_targets_path %>

app/views/beam_targets/index.html.erb
<h1>Listing beam_targets</h1>

<table>
  <tr>
    <th>Density</th>
    <th>Volume</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beam_targets.each do |beam_target| %>
  <tr>
    <td><%= beam_target.density %></td>
    <td><%= beam_target.volume %></td>
    <td><%= link_to 'Show', beam_target %></td>
    <td><%= link_to 'Edit', edit_beam_target_path(beam_target) %></td>
    <td><%= link_to 'Destroy', beam_target, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beam target', new_beam_target_path %>

app/views/beam_targets/new.html.erb
<h1>New beam_target</h1>

<%= render 'form' %>

<%= link_to 'Back', beam_targets_path %>

app/views/beam_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Density:</b>
  <%= @beam_target.density %>
</p>

<p>
  <b>Volume:</b>
  <%= @beam_target.volume %>
</p>


<%= link_to 'Edit', edit_beam_target_path(@beam_target) %> |
<%= link_to 'Back', beam_targets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>evpTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :beam_target_id %><br />
    <%= f.number_field :beam_target_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Beamtarget</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.user_id %></td>
    <td><%= reservation.beam_target_id %></td>
    <td><%= reservation.date %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @reservation.user_id %>
</p>

<p>
  <b>Beamtarget:</b>
  <%= @reservation.beam_target_id %>
</p>

<p>
  <b>Date:</b>
  <%= @reservation.date %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Lastname</th>
    <th>Firstname</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.lastname %></td>
    <td><%= user.firstname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>